import { Job, Profile, Page, Division, AppNotification } from '@/types';

// Mock Current User (Default Admin)
export const MOCK_ADMIN_USER: Profile = {
  id: 'mock-user-admin-1',
  email: 'wafflegilang@gmail.com',
  fullName: 'Gimigkk',
  phoneNumber: '081932062070',
  avatarUrl: 'https://images.unsplash.com/photo-1533738363-b7f9aef128ce?w=150&auto=format&fit=crop&q=80',
  role: 'admin',
  divisionId: 'div-4', // Creative & Marketing
  divisionName: 'Creative & Marketing',
  isApproved: true,
  createdAt: '2026-01-01T00:00:00.000Z',
  updatedAt: '2026-08-30T00:00:00.000Z',
};

export const MOCK_USERS: Profile[] = [
  MOCK_ADMIN_USER,
  {
    id: 'mock-user-des-1',
    email: 'sarah.designer@ipb.ac.id',
    fullName: 'Sarah Putri',
    phoneNumber: '081298765432',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    role: 'designer',
    divisionId: 'div-4',
    divisionName: 'Creative & Marketing',
    isApproved: true,
    lastSeenAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(), // 5 mins ago
    createdAt: '2026-02-01T00:00:00.000Z',
    updatedAt: '2026-08-30T00:00:00.000Z',
  },
  {
    id: 'mock-user-des-2',
    email: 'fauzi.creative@ipb.ac.id',
    fullName: 'Ahmad Fauzi',
    phoneNumber: '085712345678',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    role: 'designer',
    divisionId: 'div-4',
    divisionName: 'Creative & Marketing',
    isApproved: true,
    lastSeenAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(), // 2 hours ago
    createdAt: '2026-02-15T00:00:00.000Z',
    updatedAt: '2026-08-30T00:00:00.000Z',
  },
  {
    id: 'mock-user-req-1',
    email: 'bph.ipb@gmail.com',
    fullName: 'Rian Pratama',
    phoneNumber: '081345678901',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    role: 'requestor',
    divisionId: 'div-2',
    divisionName: 'Badan Pengurus Harian',
    isApproved: true,
    lastSeenAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(), // 2 days ago
    createdAt: '2026-03-01T00:00:00.000Z',
    updatedAt: '2026-08-30T00:00:00.000Z',
  },
  {
    id: 'mock-user-bunga',
    email: 'bunga@ipb.ac.id',
    fullName: 'bunga',
    phoneNumber: null,
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    role: 'designer',
    divisionId: 'div-4',
    divisionName: 'Creative & Marketing',
    isApproved: true,
    lastSeenAt: new Date(Date.now() - 120 * 24 * 60 * 60 * 1000).toISOString(), // 4 months ago
    createdAt: '2025-10-01T00:00:00.000Z',
    updatedAt: '2026-04-20T00:00:00.000Z',
  },
  {
    id: 'mock-user-faisal',
    email: 'faisalmzhdtt@ipb.ac.id',
    fullName: 'faisalmzhdtt',
    phoneNumber: null,
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    role: 'requestor',
    divisionId: 'div-1',
    divisionName: 'Academic & Publication',
    isApproved: true,
    lastSeenAt: new Date(Date.now() - 270 * 24 * 60 * 60 * 1000).toISOString(), // 9 months ago
    createdAt: '2025-05-15T00:00:00.000Z',
    updatedAt: '2025-11-10T00:00:00.000Z',
  },
  {
    id: 'mock-user-pending-1',
    email: 'farhan.partner@ipb.ac.id',
    fullName: 'Farhan Rasyid',
    phoneNumber: '081233445566',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    role: 'requestor',
    divisionId: 'div-7',
    divisionName: 'Partnership',
    isApproved: false,
    createdAt: '2026-08-28T10:00:00.000Z',
    updatedAt: '2026-08-28T10:00:00.000Z',
  },
];

export const MOCK_DIVISIONS: Division[] = [
  { id: 'div-1', name: 'Academic & Publication', createdAt: '2026-01-01T00:00:00.000Z', updatedAt: '2026-01-01T00:00:00.000Z' },
  { id: 'div-2', name: 'Badan Pengurus Harian', createdAt: '2026-01-01T00:00:00.000Z', updatedAt: '2026-01-01T00:00:00.000Z' },
  { id: 'div-3', name: 'Business Development', createdAt: '2026-01-01T00:00:00.000Z', updatedAt: '2026-01-01T00:00:00.000Z' },
  { id: 'div-4', name: 'Creative & Marketing', createdAt: '2026-01-01T00:00:00.000Z', updatedAt: '2026-01-01T00:00:00.000Z' },
  { id: 'div-5', name: 'Information', createdAt: '2026-01-01T00:00:00.000Z', updatedAt: '2026-01-01T00:00:00.000Z' },
  { id: 'div-6', name: 'Internal Humaniores', createdAt: '2026-01-01T00:00:00.000Z', updatedAt: '2026-01-01T00:00:00.000Z' },
  { id: 'div-7', name: 'Partnership', createdAt: '2026-01-01T00:00:00.000Z', updatedAt: '2026-01-01T00:00:00.000Z' },
  { id: 'div-8', name: 'Project & Competition', createdAt: '2026-01-01T00:00:00.000Z', updatedAt: '2026-01-01T00:00:00.000Z' },
  { id: 'div-9', name: 'Recruitment & Retention', createdAt: '2026-01-01T00:00:00.000Z', updatedAt: '2026-01-01T00:00:00.000Z' },
];

export const MOCK_PAGES: Page[] = [
  {
    id: 'mock-page-1',
    name: "Creative n' Marketing 2026",
    description: 'Papan kerja utama tim Creative & Media COPM',
    createdBy: 'mock-user-admin-1',
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
  },
  {
    id: 'mock-page-2',
    name: 'Dokumentasi & Publikasi Event',
    description: 'Publikasi visual khusus agenda Dies Natalis dan Seminar',
    createdBy: 'mock-user-admin-1',
    createdAt: '2026-02-01T00:00:00.000Z',
    updatedAt: '2026-02-01T00:00:00.000Z',
  },
];

export const MOCK_JOBS: Job[] = [
  // --- Antrian (In Queue) ---
  {
    id: 'mock-job-1',
    title: 'Key Visual & Banner Peluncuran Q4',
    description: 'Desain banner utama resolusi tinggi untuk portal web dan poster cetak A2.',
    briefLink: 'https://docs.google.com/document/d/1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms',
    briefTitle: 'Key Visual Q4 IEEE Launch Brief',
    publicationMedia: 'Cetak Poster & Web Banner',
    divisionId: 'div-2',
    divisionName: 'Badan Pengurus Harian',
    status: 'in_queue',
    kanbanOrder: 0,
    pageId: 'mock-page-1',
    requestorId: 'mock-user-req-1',
    requestor: MOCK_USERS[3],
    designerId: null,
    designer: null,
    designerIds: [],
    designers: [],
    deadline: '2026-09-18T00:00:00.000Z',
    isArchived: false,
    archivedAt: null,
    createdAt: '2026-09-02T10:00:00.000Z',
    updatedAt: '2026-09-02T10:00:00.000Z',
  },
  {
    id: 'mock-job-2',
    title: 'Poster Open Recruitment Staff Baru 2026',
    description: 'Poster promosi rekrutmen gelombang 2 dengan visual dinamis IEEE Student Branch.',
    briefLink: 'https://docs.google.com/document/d/1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms',
    briefTitle: 'Brief Oprec Staff Baru 2026',
    publicationMedia: 'Instagram Story & Feed A4',
    divisionId: 'div-9',
    divisionName: 'Recruitment & Retention',
    status: 'in_queue',
    kanbanOrder: 1,
    pageId: 'mock-page-1',
    requestorId: 'mock-user-req-1',
    requestor: MOCK_USERS[3],
    designerId: null,
    designer: null,
    designerIds: [],
    designers: [],
    deadline: '2026-09-15T00:00:00.000Z',
    isArchived: false,
    archivedAt: null,
    createdAt: '2026-09-01T14:00:00.000Z',
    updatedAt: '2026-09-01T14:00:00.000Z',
  },
  {
    id: 'mock-job-3',
    title: 'Company Sponsorship Booklet & Proposal Deck',
    description: 'Proposal sponsorship 12 halaman format PDF landscape untuk mitra industri B2B.',
    briefLink: 'https://docs.google.com/document/d/1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms',
    briefTitle: 'Sponsorship Deck Pitch Brief',
    publicationMedia: 'PDF Booklet & Poster',
    divisionId: 'div-7',
    divisionName: 'Partnership',
    status: 'in_queue',
    kanbanOrder: 2,
    pageId: 'mock-page-1',
    requestorId: 'mock-user-req-1',
    requestor: MOCK_USERS[3],
    designerId: null,
    designer: null,
    designerIds: [],
    designers: [],
    deadline: '2026-09-22T00:00:00.000Z',
    isArchived: false,
    archivedAt: null,
    createdAt: '2026-09-02T16:00:00.000Z',
    updatedAt: '2026-09-02T16:00:00.000Z',
  },

  // --- Sedang Dikerjakan (WIP) ---
  {
    id: 'mock-job-4',
    title: 'Carousel Feed Instagram: Tips Desain UI/UX',
    description: 'Konten edukasi 6 slide seputar Figma component system dan best practice auto-layout.',
    briefLink: 'https://docs.google.com/document/d/1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms',
    briefTitle: 'Instagram Educational Post Brief',
    publicationMedia: 'Instagram Carousel (1080x1350)',
    divisionId: 'div-4',
    divisionName: 'Creative & Marketing',
    status: 'wip',
    kanbanOrder: 0,
    pageId: 'mock-page-1',
    requestorId: 'mock-user-admin-1',
    requestor: MOCK_ADMIN_USER,
    designerId: MOCK_ADMIN_USER.id,
    designer: MOCK_ADMIN_USER,
    designerIds: [MOCK_ADMIN_USER.id, MOCK_USERS[1].id],
    designers: [MOCK_ADMIN_USER, MOCK_USERS[1]],
    deadline: '2026-09-12T00:00:00.000Z',
    isArchived: false,
    archivedAt: null,
    createdAt: '2026-08-30T09:00:00.000Z',
    updatedAt: '2026-09-01T11:00:00.000Z',
  },
  {
    id: 'mock-job-5',
    title: 'Flyer Call for Volunteers Tech Fair 2026',
    description: 'Flyer rekrutmen panitia relawan Tech Fair se-Jabodetabek format Instagram & cetak.',
    briefLink: 'https://docs.google.com/document/d/1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms',
    briefTitle: 'Call for Volunteers Tech Fair Brief',
    publicationMedia: 'Instagram Feed & Story',
    divisionId: 'div-8',
    divisionName: 'Project & Competition',
    status: 'wip',
    kanbanOrder: 1,
    pageId: 'mock-page-1',
    requestorId: 'mock-user-req-1',
    requestor: MOCK_USERS[3],
    designerId: MOCK_USERS[2].id,
    designer: MOCK_USERS[2],
    designerIds: [MOCK_USERS[2].id],
    designers: [MOCK_USERS[2]],
    deadline: '2026-09-14T00:00:00.000Z',
    isArchived: false,
    archivedAt: null,
    createdAt: '2026-08-31T08:00:00.000Z',
    updatedAt: '2026-09-01T10:00:00.000Z',
  },

  // --- Revisi (Revisions) ---
  {
    id: 'mock-job-6',
    title: 'Cover & Flyer Call for Paper 2026',
    description: 'Flyer digital untuk promosi call for paper internasional IEEE Student Branch IPB.',
    briefLink: 'https://docs.google.com/document/d/1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms',
    briefTitle: 'IEEE Call for Paper Brief',
    publicationMedia: 'Instagram Story & PDF',
    divisionId: 'div-1',
    divisionName: 'Academic & Publication',
    status: 'revisions',
    kanbanOrder: 0,
    pageId: 'mock-page-1',
    requestorId: 'mock-user-req-1',
    requestor: MOCK_USERS[3],
    designerId: MOCK_USERS[2].id,
    designer: MOCK_USERS[2],
    designerIds: [MOCK_USERS[2].id],
    designers: [MOCK_USERS[2]],
    deadline: '2026-09-11T00:00:00.000Z',
    isArchived: false,
    archivedAt: null,
    createdAt: '2026-08-28T08:00:00.000Z',
    updatedAt: '2026-09-02T14:00:00.000Z',
  },
  {
    id: 'mock-job-7',
    title: 'Merchandise T-Shirt & Lanyard Panitia',
    description: 'Desain sablon kaos combed 24s dan tali lanyard printing 2cm untuk panitia inti.',
    briefLink: 'https://docs.google.com/document/d/1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms',
    briefTitle: 'Merch Dies Natalis Brief',
    publicationMedia: 'Mockup T-Shirt & Vector AI',
    divisionId: 'div-3',
    divisionName: 'Business Development',
    status: 'revisions',
    kanbanOrder: 1,
    pageId: 'mock-page-1',
    requestorId: 'mock-user-req-1',
    requestor: MOCK_USERS[3],
    designerId: MOCK_USERS[1].id,
    designer: MOCK_USERS[1],
    designerIds: [MOCK_USERS[1].id],
    designers: [MOCK_USERS[1]],
    deadline: '2026-09-13T00:00:00.000Z',
    isArchived: false,
    archivedAt: null,
    createdAt: '2026-08-29T11:00:00.000Z',
    updatedAt: '2026-09-02T15:00:00.000Z',
  },

  // --- Selesai (Done) ---
  {
    id: 'mock-job-8',
    title: 'Twibbon & Virtual Background Rapat Pleno',
    description: 'Twibbon PNG transparan dan background Zoom 1920x1080.',
    briefLink: 'https://docs.google.com/document/d/1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms',
    briefTitle: 'Twibbon Pleno Brief',
    publicationMedia: 'Zoom Virtual Background & Twibbon',
    divisionId: 'div-9',
    divisionName: 'Recruitment & Retention',
    status: 'done',
    kanbanOrder: 0,
    pageId: 'mock-page-1',
    requestorId: 'mock-user-req-1',
    requestor: MOCK_USERS[3],
    designerId: MOCK_USERS[1].id,
    designer: MOCK_USERS[1],
    designerIds: [MOCK_USERS[1].id],
    designers: [MOCK_USERS[1]],
    deadline: '2026-09-10T00:00:00.000Z',
    isArchived: false,
    archivedAt: null,
    createdAt: '2026-08-27T08:00:00.000Z',
    updatedAt: '2026-09-02T16:00:00.000Z',
  },
  {
    id: 'mock-job-9',
    title: 'Sertifikat Pemateri Seminar Nasional Robotika',
    description: 'Sertifikat apresiasi pembicara seminar berformat cetak A4 dengan foil gold accent.',
    briefLink: 'https://docs.google.com/document/d/1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms',
    briefTitle: 'Sertifikat Seminar Robotika Brief',
    publicationMedia: 'Sertifikat Cetak A4 & e-Certificate',
    divisionId: 'div-1',
    divisionName: 'Academic & Publication',
    status: 'done',
    kanbanOrder: 1,
    pageId: 'mock-page-1',
    requestorId: 'mock-user-req-1',
    requestor: MOCK_USERS[3],
    designerId: MOCK_ADMIN_USER.id,
    designer: MOCK_ADMIN_USER,
    designerIds: [MOCK_ADMIN_USER.id],
    designers: [MOCK_ADMIN_USER],
    deadline: '2026-09-09T00:00:00.000Z',
    isArchived: false,
    archivedAt: null,
    createdAt: '2026-08-25T10:00:00.000Z',
    updatedAt: '2026-09-01T18:00:00.000Z',
  },
  {
    id: 'mock-job-10',
    title: 'Feed Instagram: Recap Acara Welcoming Party',
    description: 'Post dokumentasi foto keseruan welcoming party staff baru 2026.',
    briefLink: 'https://docs.google.com/document/d/1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms',
    briefTitle: 'Recap Welcoming Party Brief',
    publicationMedia: 'Instagram Carousel 5 Slide',
    divisionId: 'div-4',
    divisionName: 'Creative & Marketing',
    status: 'done',
    kanbanOrder: 2,
    pageId: 'mock-page-1',
    requestorId: 'mock-user-admin-1',
    requestor: MOCK_ADMIN_USER,
    designerId: MOCK_USERS[1].id,
    designer: MOCK_USERS[1],
    designerIds: [MOCK_USERS[1].id],
    designers: [MOCK_USERS[1]],
    deadline: '2026-09-08T00:00:00.000Z',
    isArchived: false,
    archivedAt: null,
    createdAt: '2026-08-24T09:00:00.000Z',
    updatedAt: '2026-08-30T17:00:00.000Z',
  },

  // --- Archived Jobs (Archive Table) ---
  {
    id: 'mock-job-11',
    title: 'Poster Kemitraan Industri & Sponsor Tech Expo',
    description: 'Proposal booklet visual untuk pengajuan sponsor kemitraan perusahaan.',
    briefLink: 'https://docs.google.com/document/d/1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms',
    briefTitle: 'Sponsorship Partner Deck Brief',
    publicationMedia: 'PDF Booklet & Poster',
    divisionId: 'div-7',
    divisionName: 'Partnership',
    status: 'done',
    kanbanOrder: 0,
    pageId: 'mock-page-1',
    requestorId: 'mock-user-req-1',
    requestor: MOCK_USERS[3],
    designerId: MOCK_ADMIN_USER.id,
    designer: MOCK_ADMIN_USER,
    designerIds: [MOCK_ADMIN_USER.id],
    designers: [MOCK_ADMIN_USER],
    deadline: '2026-08-25T00:00:00.000Z',
    isArchived: true,
    archivedAt: '2026-08-26T00:00:00.000Z',
    createdAt: '2026-08-20T08:00:00.000Z',
    updatedAt: '2026-08-26T00:00:00.000Z',
  },
  {
    id: 'mock-job-12',
    title: 'Banner Booth Expo Kampus IPB 2025',
    description: 'Roll-up banner ukuran 80x200cm untuk pameran UKM dan organisasi kampus.',
    briefLink: 'https://docs.google.com/document/d/1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms',
    briefTitle: 'Roll Up Banner Expo Brief',
    publicationMedia: 'Roll-up Banner 80x200cm',
    divisionId: 'div-4',
    divisionName: 'Creative & Marketing',
    status: 'done',
    kanbanOrder: 1,
    pageId: 'mock-page-1',
    requestorId: 'mock-user-admin-1',
    requestor: MOCK_ADMIN_USER,
    designerId: MOCK_USERS[1].id,
    designer: MOCK_USERS[1],
    designerIds: [MOCK_USERS[1].id],
    designers: [MOCK_USERS[1]],
    deadline: '2026-08-15T00:00:00.000Z',
    isArchived: true,
    archivedAt: '2026-08-16T00:00:00.000Z',
    createdAt: '2026-08-10T08:00:00.000Z',
    updatedAt: '2026-08-16T00:00:00.000Z',
  },
  {
    id: 'mock-job-13',
    title: 'Desain Infografis Laporan Keuangan Semester 1',
    description: 'Infografis transparansi kas dan alokasi anggaran program kerja.',
    briefLink: 'https://docs.google.com/document/d/1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms',
    briefTitle: 'Infografis Keuangan Brief',
    publicationMedia: 'Instagram Carousel 4 Slide',
    divisionId: 'div-2',
    divisionName: 'Badan Pengurus Harian',
    status: 'done',
    kanbanOrder: 2,
    pageId: 'mock-page-1',
    requestorId: 'mock-user-req-1',
    requestor: MOCK_USERS[3],
    designerId: MOCK_USERS[2].id,
    designer: MOCK_USERS[2],
    designerIds: [MOCK_USERS[2].id],
    designers: [MOCK_USERS[2]],
    deadline: '2026-08-22T00:00:00.000Z',
    isArchived: true,
    archivedAt: '2026-08-23T00:00:00.000Z',
    createdAt: '2026-08-15T08:00:00.000Z',
    updatedAt: '2026-08-23T00:00:00.000Z',
  },
  {
    id: 'mock-job-14',
    title: 'Template Instagram Story Interaktif Tanya Jawab',
    description: 'Template visual story bertema modern clean untuk quiz dan Q&A staff.',
    briefLink: 'https://docs.google.com/document/d/1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms',
    briefTitle: 'Template IG Story Brief',
    publicationMedia: 'Figma Assets & PNG Story',
    divisionId: 'div-4',
    divisionName: 'Creative & Marketing',
    status: 'done',
    kanbanOrder: 3,
    pageId: 'mock-page-1',
    requestorId: 'mock-user-admin-1',
    requestor: MOCK_ADMIN_USER,
    designerId: MOCK_USERS[2].id,
    designer: MOCK_USERS[2],
    designerIds: [MOCK_USERS[2].id],
    designers: [MOCK_USERS[2]],
    deadline: '2026-08-28T00:00:00.000Z',
    isArchived: true,
    archivedAt: '2026-08-29T00:00:00.000Z',
    createdAt: '2026-08-21T09:00:00.000Z',
    updatedAt: '2026-08-29T00:00:00.000Z',
  },
  {
    id: 'mock-job-15',
    title: 'Virtual Background Zoom Kuliah Umum Keteknikan',
    description: 'Desain latar belakang virtual resmi fakultas beresolusi Full HD.',
    briefLink: 'https://docs.google.com/document/d/1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms',
    briefTitle: 'Virtual Background Kuliah Umum',
    publicationMedia: 'Zoom Virtual Background',
    divisionId: 'div-1',
    divisionName: 'Academic & Publication',
    status: 'done',
    kanbanOrder: 4,
    pageId: 'mock-page-1',
    requestorId: 'mock-user-req-1',
    requestor: MOCK_USERS[3],
    designerId: MOCK_USERS[1].id,
    designer: MOCK_USERS[1],
    designerIds: [MOCK_USERS[1].id],
    designers: [MOCK_USERS[1]],
    deadline: '2026-08-18T00:00:00.000Z',
    isArchived: true,
    archivedAt: '2026-08-19T00:00:00.000Z',
    createdAt: '2026-08-12T10:00:00.000Z',
    updatedAt: '2026-08-19T00:00:00.000Z',
  },
  {
    id: 'mock-job-16',
    title: 'Kartu Nama & ID Badge Dewan Penasehat Organisasi',
    description: 'Desain ID Card PVC vertikal ukuran kartu standar dengan lanyard biru navy.',
    briefLink: 'https://docs.google.com/document/d/1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms',
    briefTitle: 'ID Card Dewan Penasehat Brief',
    publicationMedia: 'Cetak ID Card PVC',
    divisionId: 'div-2',
    divisionName: 'Badan Pengurus Harian',
    status: 'done',
    kanbanOrder: 5,
    pageId: 'mock-page-1',
    requestorId: 'mock-user-req-1',
    requestor: MOCK_USERS[3],
    designerId: MOCK_ADMIN_USER.id,
    designer: MOCK_ADMIN_USER,
    designerIds: [MOCK_ADMIN_USER.id],
    designers: [MOCK_ADMIN_USER],
    deadline: '2026-08-25T00:00:00.000Z',
    isArchived: true,
    archivedAt: '2026-08-25T00:00:00.000Z',
    createdAt: '2026-08-18T11:00:00.000Z',
    updatedAt: '2026-08-25T00:00:00.000Z',
  },
  {
    id: 'mock-job-17',
    title: 'Flyer Workshop UI/UX Design System Figma 2026',
    description: 'Flyer promosi pelatihan Figma intensif bagi desainer muda kampus.',
    briefLink: 'https://docs.google.com/document/d/1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms',
    briefTitle: 'Flyer Workshop UI/UX Brief',
    publicationMedia: 'Instagram Story & Feed A4',
    divisionId: 'div-4',
    divisionName: 'Creative & Marketing',
    status: 'done',
    kanbanOrder: 6,
    pageId: 'mock-page-1',
    requestorId: 'mock-user-admin-1',
    requestor: MOCK_ADMIN_USER,
    designerId: MOCK_USERS[2].id,
    designer: MOCK_USERS[2],
    designerIds: [MOCK_USERS[2].id],
    designers: [MOCK_USERS[2]],
    deadline: '2026-09-01T00:00:00.000Z',
    isArchived: true,
    archivedAt: '2026-09-02T00:00:00.000Z',
    createdAt: '2026-08-26T14:00:00.000Z',
    updatedAt: '2026-09-02T00:00:00.000Z',
  },
  {
    id: 'mock-job-18',
    title: 'Ilustrasi Maskot Dies Natalis Resolusi Tinggi',
    description: 'Artwork vector maskot karakter dies natalis format SVG dan PNG transparent.',
    briefLink: 'https://docs.google.com/document/d/1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms',
    briefTitle: 'Maskot Vector Dies Natalis',
    publicationMedia: 'Vector SVG & PNG Transparent',
    divisionId: 'div-4',
    divisionName: 'Creative & Marketing',
    status: 'done',
    kanbanOrder: 7,
    pageId: 'mock-page-1',
    requestorId: 'mock-user-admin-1',
    requestor: MOCK_ADMIN_USER,
    designerId: MOCK_USERS[1].id,
    designer: MOCK_USERS[1],
    designerIds: [MOCK_USERS[1].id],
    designers: [MOCK_USERS[1]],
    deadline: '2026-08-31T00:00:00.000Z',
    isArchived: true,
    archivedAt: '2026-09-01T00:00:00.000Z',
    createdAt: '2026-08-25T16:00:00.000Z',
    updatedAt: '2026-09-01T00:00:00.000Z',
  },

  // --- Workspace 2: Dokumentasi & Publikasi Event (mock-page-2) ---
  {
    id: 'mock-job-p2-1',
    title: 'Dokumentasi Foto Wisuda Sarjana & Magister IPB',
    description: 'Liputan fotografi profesional prosesi wisuda mahasiswa tingkat akhir.',
    briefLink: 'https://docs.google.com/document/d/1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms',
    briefTitle: 'Dokumentasi Wisuda Brief',
    publicationMedia: 'Google Drive Archive & Instagram',
    divisionId: 'div-4',
    divisionName: 'Creative & Marketing',
    status: 'in_queue',
    kanbanOrder: 0,
    pageId: 'mock-page-2',
    requestorId: 'mock-user-admin-1',
    requestor: MOCK_ADMIN_USER,
    designerId: null,
    designer: null,
    designerIds: [],
    designers: [],
    deadline: '2026-09-25T00:00:00.000Z',
    isArchived: false,
    archivedAt: null,
    createdAt: '2026-09-02T08:00:00.000Z',
    updatedAt: '2026-09-02T08:00:00.000Z',
  },
  {
    id: 'mock-job-p2-2',
    title: 'Live Streaming Youtube: Seminar Internasional Bio-Tech',
    description: 'Setup broadcast OBS multi-camera dan lower-thirds grafik siaran langsung.',
    briefLink: 'https://docs.google.com/document/d/1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms',
    briefTitle: 'Live Streaming OBS Setup Brief',
    publicationMedia: 'Youtube Live 1080p60',
    divisionId: 'div-1',
    divisionName: 'Academic & Publication',
    status: 'wip',
    kanbanOrder: 0,
    pageId: 'mock-page-2',
    requestorId: 'mock-user-req-1',
    requestor: MOCK_USERS[3],
    designerId: MOCK_ADMIN_USER.id,
    designer: MOCK_ADMIN_USER,
    designerIds: [MOCK_ADMIN_USER.id],
    designers: [MOCK_ADMIN_USER],
    deadline: '2026-09-17T00:00:00.000Z',
    isArchived: false,
    archivedAt: null,
    createdAt: '2026-09-01T10:00:00.000Z',
    updatedAt: '2026-09-02T12:00:00.000Z',
  },
  {
    id: 'mock-job-p2-3',
    title: 'Reel Video Teaser: Dies Natalis ke-10 IEEE IPB',
    description: 'Short video vertical 9:16 durasi 30 detik untuk teaser pembukaan acara.',
    briefLink: 'https://docs.google.com/document/d/1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms',
    briefTitle: 'Teaser Video Reels Brief',
    publicationMedia: 'Instagram Reels & TikTok (9:16)',
    divisionId: 'div-4',
    divisionName: 'Creative & Marketing',
    status: 'revisions',
    kanbanOrder: 0,
    pageId: 'mock-page-2',
    requestorId: 'mock-user-admin-1',
    requestor: MOCK_ADMIN_USER,
    designerId: MOCK_USERS[1].id,
    designer: MOCK_USERS[1],
    designerIds: [MOCK_USERS[1].id],
    designers: [MOCK_USERS[1]],
    deadline: '2026-09-12T00:00:00.000Z',
    isArchived: false,
    archivedAt: null,
    createdAt: '2026-08-30T10:00:00.000Z',
    updatedAt: '2026-09-02T14:00:00.000Z',
  },
  {
    id: 'mock-job-p2-4',
    title: 'Liputan Media & Press Release Portal Kampus IPB',
    description: 'Artikel berita dan foto dokumentasi kegiatan seminar nasional.',
    briefLink: 'https://docs.google.com/document/d/1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms',
    briefTitle: 'Press Release Media Brief',
    publicationMedia: 'Portal Berita Kampus & LinkedIn',
    divisionId: 'div-7',
    divisionName: 'Partnership',
    status: 'done',
    kanbanOrder: 0,
    pageId: 'mock-page-2',
    requestorId: 'mock-user-req-1',
    requestor: MOCK_USERS[3],
    designerId: MOCK_USERS[2].id,
    designer: MOCK_USERS[2],
    designerIds: [MOCK_USERS[2].id],
    designers: [MOCK_USERS[2]],
    deadline: '2026-09-08T00:00:00.000Z',
    isArchived: false,
    archivedAt: null,
    createdAt: '2026-08-28T09:00:00.000Z',
    updatedAt: '2026-09-01T15:00:00.000Z',
  },
];

export const MOCK_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'mock-notif-1',
    userId: 'mock-user-admin-1',
    title: 'Request Baru Diajukan',
    message: 'Divisi Badan Pengurus Harian mengajukan job: "Key Visual & Banner Peluncuran Q4"',
    type: 'job_created',
    isRead: false,
    jobId: 'mock-job-1',
    createdAt: '2026-08-29T10:00:00.000Z',
  },
  {
    id: 'mock-notif-2',
    userId: 'mock-user-admin-1',
    title: 'Permintaan Revisi Desain',
    message: 'Job "Cover & Flyer Call for Paper 2026" membutuhkan revisi logo.',
    type: 'job_revisions',
    isRead: true,
    jobId: 'mock-job-3',
    createdAt: '2026-08-29T14:00:00.000Z',
  },
];

// Global mutable store for in-memory dev mutations
class MockStore {
  users: Profile[] = JSON.parse(JSON.stringify(MOCK_USERS));
  divisions: Division[] = JSON.parse(JSON.stringify(MOCK_DIVISIONS));
  pages: Page[] = JSON.parse(JSON.stringify(MOCK_PAGES));
  jobs: Job[] = JSON.parse(JSON.stringify(MOCK_JOBS));
  notifications: AppNotification[] = JSON.parse(JSON.stringify(MOCK_NOTIFICATIONS));
  currentUser: Profile = JSON.parse(JSON.stringify(MOCK_ADMIN_USER));
}

declare global {
  var __COPM_MOCK_STORE__: MockStore | undefined;
}

export function getMockStore(): MockStore {
  if (!global.__COPM_MOCK_STORE__) {
    global.__COPM_MOCK_STORE__ = new MockStore();
  }
  return global.__COPM_MOCK_STORE__;
}

export function resetMockStore(): MockStore {
  global.__COPM_MOCK_STORE__ = new MockStore();
  return global.__COPM_MOCK_STORE__;
}

export function isMockEnabled(): boolean {
  return process.env.USE_MOCK_DATA === 'true';
}
